name: Bug report
description: Report a reproducible bug in the project
labels:
  - a:bug
body:
  - type: markdown
    attributes:
      value: |
        Please follow the instructions below. We receive dozens of issues every week,
        so to stay productive, we will close issues that don't provide enough information.

        Please open Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

        Provide a brief summary of the issue in the title above
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Context
      description: How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a self-contained example project (as an attached archive or a Github project). In the rare cases where this is infeasible, we will also accept a detailed set of instructions.
  - type: input
    attributes:
      label: Your Environment
      description: Include as many relevant details about the environment you experienced the bug in. A build scan `https://scans.gradle.com/get-started` is ideal.
      placeholder: "https://scans.gradle.com/s/..."
