name: Feature request
description: Suggest a new feature or improvement
labels:
  - a:feature
body:
  - type: markdown
    attributes:
      value: |
        Please follow the instructions below. We receive dozens of issues every week,
        so to stay productive, we will close issues that don't provide enough information.

        Please open Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

        Provide a brief summary of the issue in the title above
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Tell us how this feature should work.
  - type: textarea
    attributes:
      label: Current Behavior
      description: Explain the difference from current behavior.
  - type: textarea
    attributes:
      label: Context
      description: How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.
  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any other relevant context or information that you think may be relevant for this feature request.
